#!/usr/bin/env bash
# Set up a macOS build of the OBS plugin, and configure build-obs against it.
#
# Why this exists: the SDK and dependencies used to be fetched into a temporary
# directory, which macOS clears on reboot — so build-obs pointed at a path that
# had ceased to exist and `cmake --build` failed with "obs-module.h not found".
# Everything now lands in ~/Library/Caches, which survives a restart.
#
# The recipe itself is not obvious and was previously only written down inside
# .github/workflows/obs-plugin.yml. Two parts of it are easy to get wrong:
#
#   obsconfig.h  is GENERATED by OBS's own build and is not in the source
#                tarball. A plugin needs two defines from it, so a stub is
#                stood up here rather than configuring the whole of OBS.
#   ENABLE_QT    defaults to OFF, which builds a plugin with no docks at all.
#                It has to be asked for, along with every FFmpeg path pinned to
#                the deps tree — Homebrew's FFmpeg and Qt are found first
#                otherwise, and produce a plugin that loads and then misbehaves
#                against a different library than OBS is running.
#
# Idempotent: re-run it any time. Downloads are skipped if already present.
set -euo pipefail

OBS_TAG="${OBS_TAG:-32.2.2}"
CACHE="${OBS_BUILD_CACHE:-$HOME/Library/Caches/obs-multisite-build}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "OBS ${OBS_TAG}, cache ${CACHE}"
mkdir -p "${CACHE}/deps/root" "${CACHE}/gen"
cd "${CACHE}"

# The obs-deps version is whatever OBS pins for this release; guessing it is how
# you end up building against a different FFmpeg than the host application.
VER="${OBS_DEPS_VERSION:-}"
if [ -z "${VER}" ]; then
  curl -sfSL -o presets.json \
    "https://raw.githubusercontent.com/obsproject/obs-studio/${OBS_TAG}/CMakePresets.json"
  VER=$(python3 -c "import json;d=json.load(open('presets.json'));print(next((p['vendor']['obsproject.com/obs-studio']['dependencies']['prebuilt']['version'] for p in d.get('configurePresets',[]) if p.get('name')=='dependencies'),''))")
fi
[ -n "${VER}" ] || { echo "could not read the obs-deps version OBS pins" >&2; exit 1; }
echo "obs-deps ${VER}"

for name in "macos-deps-${VER}-arm64.tar.xz" "macos-deps-qt6-${VER}-arm64.tar.xz"; do
  if [ ! -f "${name}" ]; then
    echo "fetching ${name}"
    curl -sfSL -o "${name}" \
      "https://github.com/obsproject/obs-deps/releases/download/${VER}/${name}"
    tar xf "${name}" -C deps/root
  fi
done

OBS_SRC="${CACHE}/obs-studio-${OBS_TAG}"
if [ ! -f "${OBS_SRC}/libobs/obs-module.h" ]; then
  echo "fetching obs-studio ${OBS_TAG} (headers only)"
  curl -sfSL -o obs.tar.gz \
    "https://github.com/obsproject/obs-studio/archive/refs/tags/${OBS_TAG}.tar.gz"
  tar xzf obs.tar.gz && rm -f obs.tar.gz
fi
test -f "${OBS_SRC}/libobs/obs-module.h"

printf '%s\n' '#pragma once' '#define OBS_RELEASE_CANDIDATE 0' '#define OBS_BETA 0' \
  > "${CACHE}/gen/obsconfig.h"

FE="${OBS_SRC}/frontend/api"
[ -d "${FE}" ] || FE="${OBS_SRC}/UI/obs-frontend-api"
test -f "${FE}/obs-frontend-api.h"

DEPS="${CACHE}/deps/root"
cd "${REPO}"

# Start clean when the existing cache points at somewhere that has gone. That
# is the reboot case this script exists for: CMake keeps the old paths, and
# reconfiguring over them fails in ways that name Qt rather than the missing
# SDK. Cheap to redo, and it removes a whole class of confusing error.
if [ -f build-obs/CMakeCache.txt ]; then
  OLD=$(sed -n 's/^LIBOBS_INCLUDE_DIR[^=]*=//p' build-obs/CMakeCache.txt | head -1)
  if [ -n "${OLD}" ] && [ ! -d "${OLD}" ]; then
    echo "existing build-obs points at a path that no longer exists — reconfiguring from scratch"
    rm -rf build-obs
  fi
fi

cmake -S . -B build-obs \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_OBS_PLUGIN=ON -DENABLE_QT=ON \
  -DCMAKE_PREFIX_PATH="${DEPS}" \
  -DQt6_DIR="${DEPS}/lib/cmake/Qt6" \
  -DFORCE_FFMPEG_MANUAL_SEARCH=ON \
  -DFFMPEG_INCLUDE_DIR="${DEPS}/include" \
  -DFFMPEG_avformat_LIBRARY="${DEPS}/lib/libavformat.dylib" \
  -DFFMPEG_avcodec_LIBRARY="${DEPS}/lib/libavcodec.dylib" \
  -DFFMPEG_avutil_LIBRARY="${DEPS}/lib/libavutil.dylib" \
  -DFFMPEG_swresample_LIBRARY="${DEPS}/lib/libswresample.dylib" \
  -DFFMPEG_swscale_LIBRARY="${DEPS}/lib/libswscale.dylib" \
  -DLIBOBS_INCLUDE_DIR="${OBS_SRC}/libobs" \
  -DLIBOBS_CONFIG_INCLUDE_DIR="${CACHE}/gen" \
  -DLIBOBS_FRONTEND_INCLUDE_DIR="${FE}"

cat <<DONE

Configured. To build and install:

  cmake --build build-obs --config Release --target obs-multisite -j
  PLUGINS="\$HOME/Library/Application Support/obs-studio/plugins"
  rm -rf "\$PLUGINS/obs-multisite.plugin"
  cp -R build-obs/obs-multisite.plugin "\$PLUGINS/"
  xattr -dr com.apple.quarantine "\$PLUGINS/obs-multisite.plugin"

Quit OBS before installing: replacing a loaded bundle is how you get a crash
that looks like a plugin fault.
DONE
